version: '3.4'

services:
  flask:
    build: ./
    container_name: flask
    environment:
      FLASK_ENV: development
      FLASK_APP: app/main
#    ports:
#      - "${PORT}:80"
#      - "5432:5432"
    volumes:
      - "./:/app"
#    command: flask run --host=0.0.0.0 --port 80
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - flask

