version: '3.4'

services:
  flask:
    build: ./
    container_name: flask
    environment:
      FLASK_ENV: development
      FLASK_APP: app/main
      UWSGI_INI: ./local.ini
    volumes:
      - "./:/app"
    depends_on:
      - redis
    ports:
      - "5000:5000"
    networks:
      - redis_nw    

  worker:
    build:
      context: ./app/celery-queue
      dockerfile: Dockerfile.dev
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    networks:
      - redis_nw
    volumes: ['./app/celery-queue:/queue']
  beat:
    build:
      context: ./app/celery-queue
      dockerfile: Dockerfile.dev
    command: celery -A tasks beat -l info
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    networks:
      - redis_nw
    volumes: ['./app/celery-queue:/queue']
  monitor:
    build:
      context: ./app/celery-queue
      dockerfile: Dockerfile.dev
    ports:
     - "5555:5555"
    command:  ['celery', 'flower', '-A', 'tasks']
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    networks:
      - redis_nw
    volumes: ['./app/celery-queue:/queue']
  redis:
    image: redis:alpine
    networks:
      - redis_nw




networks:
  redis_nw:
    driver: bridge
