[tool.poetry]
name = "flask-dash-app"
version = "0.1.0"
description = "Integrate Plotly Dash into your Flask applications."
authors = ["tzelleke <theodros.zelleke@gmail.com>"]
maintainers = ["tzelleke <theodros.zelleke@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://hackersandslackers.com/plotly-dash-with-flask/"
repository = "https://github.com/toddbirchard/plotlydash-flask-tutorial/"
documentation = "https://hackersandslackers.com/plotly-dash-with-flask/"
keywords = [
    "Flask",
    "Plotly",
    "Plotly Dash",
    "Data Science"
]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.1"
dash = "^1.21.0"
dash-bootstrap-components = "^0.12.2"
pandas = "^1.3.1"
scikit-learn = "^0.24.2"
Markdown = "^3.3.4"
python-dotenv = "^0.19.0"
Pygments = "^2.9.0"
#pygments-style-solarized = "^0.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
